<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>io.appform.memq</groupId>
        <artifactId>memq</artifactId>
        <version>5.0.2-0-1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>memq-dw-bundle</artifactId>
    <name>MemQ Actors Bundle for Dropwizard 2x</name>
    <version>5.0.2-0-1</version>
    <properties>
        <dropwizard.version>5.0.2</dropwizard.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-bom</artifactId>
                <type>pom</type>
                <scope>import</scope>
                <version>${dropwizard.version}</version>
            </dependency>
            <!-- Dropwizard Dependencies for transitive deps like hibernate-core -->
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-dependencies</artifactId>
                <type>pom</type>
                <scope>import</scope>
                <version>${dropwizard.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.appform.memq</groupId>
            <artifactId>memq-actor</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
